### ISSUE TITLE
Could not generate a proxy class for class org.sonarqube.gradle.SonarQubeTask

### ISSUE THREAD

**Issue by rahul-github** [neworld/gradle-jdeploy-plugin#5]
Hi ,

I am fairly new to the gradle tool. I am implementing the sonarqube scan in my build pipeline for my Java Project .
To do that we are bound to use the local plugin which is placed on the filesystem instead of downloading it from the online repository due to the firewall and certificate issues.

While I try to do that, I am getting the below error : 

 What went wrong:
  A problem occurred evaluating root project 'custom-extensions'.
  > Failed to apply plugin [id 'org.sonarqube']
	> Could not create task ':sonarqube'.
		> Could not generate a proxy class for class org.sonarqube.gradle.SonarQubeTask.

	* Try:
2021-06-22 12:33:36:950 GMT+05:30  Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
2021-06-22 12:33:36:950 GMT+05:30  
2021-06-22 12:33:36:950 GMT+05:30  * Get more help at https://help.gradle.org
2021-06-22 12:33:36:950 GMT+05:30  
2021-06-22 12:33:36:950 GMT+05:30  BUILD FAILED in 3s

Stack trace output :

Caused by: java.lang.NoClassDefFoundError: org/sonarsource/scanner/api/LogOutput
        at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:265)
        at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:220)
        at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:98)
        ... 55 more
Caused by: java.lang.ClassNotFoundException: org.sonarsource.scanner.api.LogOutput
        ... 58 more

My build.gradle has : 

buildscript {
  repositories {
    flatDir {
      dirs "../sonarqube-gradle-plugin-3.1"
    }
  }
  dependencies {
    classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.1"
  }
}

apply plugin: "org.sonarqube" 

The jar file for the plugin is placed under the sonarqube directory as mentioned above .

Please suggest a way to make this work.

**Comment by neworld** [comment]
Is it related to jdeploy plugin?

**Comment by rahul-github** [comment]
no its related to the sonarqube plugin for gradle.

**Comment by neworld** [comment]
You should ask in any user group of sonar. I do not use Sonar and can't help.
